name: CICD Demo class

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: |
          echo " Hello this my ${{vars.MY_APP}}"
          echo "Hello Pranit"
          echo "This is new cicd mm"
 
  
