name: GitHub Actions Demo

on:
  push:

jobs:

  action-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Print index.html file
        run: cat index.html

      - name: Build Step
        run: |
          echo "Hello this is my ${{ vars.MY_APP }}"
          echo "Hello Pranit"
          echo "This is new cicd mm"

  test:
    runs-on: ubuntu-latest
    needs: action-demo

    steps:
      - name: Test Phase
        run: echo "Running TC"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy the app
        run: |
          echo "My app password is configured"
          echo "Deploy app correctly"
```
