name: Nice if-else eg
on:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:
  quality_checks:
    if: startsWith(github.ref_name, 'feature/') && github.event_name == 'push' ## must start with feature branch 
    runs-on: ubuntu-latest
    steps:
      - name: Perform code quality
        run: echo  "Performing quality checks on the code"

  dev_deploy:
    if: github.ref_name == 'develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Dev Deploy
        run: echo "Deploying the code to dev environment"

  prod_deploy:
    if: github.ref_name == 'main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Production  Deploy
        run: echo "Deploying the code to Production environment"

  Success_notify:
    needs:
      - quality_checks
      - dev_deploy
      - prod_deploy
    if: always() && !failure()  ## can be skiped but it should not fail
    runs-on: ubuntu-latest
    steps:
      - name: Notify Success
        run: echo "Success email sent to the team"

  failure_notify:
    needs:  
      - quality_checks
      - dev_deploy
      - prod_deploy
    if: failure()  ## can be skiped but it should not fail
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure
        run: echo "failure email sent to the team"