name: Input demo
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the Environment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      artifact_tags_demo:
         description: Choose the git tag to deploy
         required: true

jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Show env and Deploy the App 
        run: echo "Deploying to the ${{ inputs.artifact_tags_demo }} in ${{inputs.environment}} evironment"
      
    
      
