name: pull_request if else
on: 
  pull_request:
    types: 
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "helllo applicatio is running"
      
